"""empty message

Revision ID: d988fb323148
Revises:
Create Date: 2021-04-02 13:14:06.231234

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd988fb323148'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['padre_id'], ['modulo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('politica',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('asignada', sa.Boolean(), nullable=False),
    sa.Column('coeficiente', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('parrafo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('secuencia', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.TEXT(), nullable=True),
    sa.Column('texto', sa.TEXT(), nullable=False),
    sa.Column('texto_html', sa.TEXT(), nullable=False),
    sa.Column('politica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['politica_id'], ['politica.id'], ),
    sa.PrimaryKeyConstraint('id', 'politica_id')
    )
    op.create_table('rol_modulo',
    sa.Column('rol_usuario_id', sa.Integer(), nullable=True),
    sa.Column('modulo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo.id'], ),
    sa.ForeignKeyConstraint(['rol_usuario_id'], ['rol_usuario.id'], )
    )
    op.create_table('tratamiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=512), nullable=False),
    sa.Column('color_primario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_primario'], ['color.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hora_registro', sa.DateTime(), nullable=False),
    sa.Column('rol_usuario', sa.Integer(), nullable=True),
    sa.Column('clave_hash', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('entrenamiento', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rol_usuario'], ['rol_usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('anotacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_anotado', sa.DateTime(), nullable=False),
    sa.Column('texto', sa.TEXT(), nullable=False),
    sa.Column('texto_html', sa.TEXT(), nullable=False),
    sa.Column('comentario', sa.TEXT(), nullable=True),
    sa.Column('parrafo_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('consolidar', sa.Boolean(), nullable=False),
    sa.Column('ejecuta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parrafo_id'], ['parrafo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atributo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tratamiento_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tratamiento_id'], ['tratamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista_negra_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('politica_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('politica_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('consolidar', sa.Boolean(), nullable=False),
    sa.Column('finalizado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['politica_id'], ['politica.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=512), nullable=False),
    sa.Column('atributo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atributo_id'], ['atributo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anotacion_valor',
    sa.Column('anotacion_id', sa.Integer(), nullable=False),
    sa.Column('valor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anotacion_id'], ['anotacion.id'], ),
    sa.ForeignKeyConstraint(['valor_id'], ['valor.id'], ),
    sa.PrimaryKeyConstraint('anotacion_id', 'valor_id')
    )

    color_table = sa.table('color',
    sa.column('id', sa.Integer),
    sa.column('codigo', sa.String),
    sa.column('disponible', sa.Boolean)
    )

    modulo_table = sa.table('modulo',
    sa.Column('id', sa.Integer),
    sa.Column('nombre', sa.String),
    sa.Column('icono', sa.String),
    sa.Column('path', sa.String),
    sa.Column('padre_id', sa.Integer),
    )

    rol_usuario_table = sa.table('rol_usuario',
    sa.Column('id', sa.Integer),
    sa.Column('nombre', sa.String),
    sa.Column('descripcion', sa.String),
    )

    rol_modulo_table = sa.table('rol_modulo',
    sa.Column('rol_usuario_id', sa.Integer),
    sa.Column('modulo_id', sa.Integer)
    )

    usuario_table = sa.table('usuario',
    sa.Column('id', sa.Integer),
    sa.Column('email', sa.String),
    sa.Column('hora_registro', sa.DateTime),
    sa.Column('rol_usuario', sa.Integer),
    sa.Column('clave_hash', sa.String),
    sa.Column('activo', sa.Boolean),
    sa.Column('entrenamiento', sa.Boolean)
    )

    # Seed database info
    op.bulk_insert(color_table,
        [
            {'id': 1, 'codigo': '#000000', 'disponible': True},
            {'id': 2, 'codigo': '#ffffff', 'disponible': True},
        ]
    )

    op.bulk_insert(modulo_table,
        [
            {'id': 1,'nombre':'raiz','icono':'','path': None,'padre_id': None},
            {'id': 2,'nombre':'Administracion','icono':'build','path': None,'padre_id':'1'},
            {'id': 3,'nombre':'Consolidacion','icono':'book','path':'/paginas/consolidacion','padre_id':'1'},
            {'id': 4,'nombre':'Anotacion','icono':'create','path':'/paginas/anotacion','padre_id':'1'},
            {'id': 5,'nombre':'Usuarios','icono':'account_circle','path':'/paginas/administracion/usuarios','padre_id':'2'},
            {'id': 6,'nombre':'Politicas','icono':'menu_book','path':'/paginas/administracion/politicas','padre_id':'2'},
            {'id': 7,'nombre':'Tratamientos','icono':'highlight','path':'/paginas/administracion/tratamientos','padre_id':'2'},
            {'id': 9,'nombre':'Atributos','icono':'format_list_bulleted','path':'/paginas/administracion/atributos','padre_id':'2'},
            {'id': 10,'nombre':'Valores','icono':'format_list_numbered','path':'/paginas/administracion/valores','padre_id':'2'}
        ]
    )

    op.bulk_insert(rol_usuario_table,
        [
            {'id': 1, 'nombre': 'Administrador', 'descripcion': 'Encargado de administrar y consolidar políticas'},
            {'id': 2, 'nombre': 'Anotador', 'descripcion': 'Encargado de anotar políticas'}
        ]
    )

    op.bulk_insert(rol_modulo_table,
        [
            {'rol_usuario_id':1, 'modulo_id':2},
            {'rol_usuario_id':1, 'modulo_id':3},
            {'rol_usuario_id':1, 'modulo_id':4},
            {'rol_usuario_id':2, 'modulo_id':4}
        ]
    )

    op.bulk_insert(usuario_table,
        [
            {
                'id': 1,
                'email':'admin@gmail.com',
                'hora_registro': datetime.now(),
                'rol_usuario': 1,
                'clave_hash': '$2b$12$gJM9bfraOtvHSPT3FVby/OQyC2FlVWaG/goYIDujTDLEELJoVkwfu',
                'activo': True,
                'entrenamiento': False
            }
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anotacion_valor')
    op.drop_table('valor')
    op.drop_table('politica_usuario')
    op.drop_table('lista_negra_tokens')
    op.drop_table('atributo')
    op.drop_table('anotacion')
    op.drop_table('usuario')
    op.drop_table('tratamiento')
    op.drop_table('rol_modulo')
    op.drop_table('parrafo')
    op.drop_table('rol_usuario')
    op.drop_table('politica')
    op.drop_table('modulo')
    op.drop_table('color')
    # ### end Alembic commands ###
